name: Upload Files

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: sa-east-1

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./ s3://pax-config-app --region sa-east-1
    - name: Ajuste Metadata do configuracoes.json
      run: aws s3 cp ./configuracoes.json s3://pax-config-app/configuracoes.json --metadata-directive REPLACE --content-type "application/json; charset=utf-8"